---
# tasks file for roles/database
- name: Create the database container
  docker_container:
    name: database
    image: lbonnieul/database
    pull: yes
    env:
      POSTGRES_DB: "db"
      POSTGRES_USER: "usr"
      POSTGRES_PASSWORD: "pwd"
    volumes:
      - volume-data:/var/lib/postgresql/data
    networks:
      - name : network-database-backend
    
    