---
# tasks file for roles/backend
- name: Create the backend container and connect it to both networks
  docker_container:
    name: backend
    image: lbonnieul/backend
    pull: yes
    env:
      DB_NAME: "db"
      DB_USER: "usr"
      DB_PASSWORD: "pwd"
    networks:
      - name: network-database-backend

      - name: network-backend-proxy
    