---
# tasks file for roles/backend
- name: Create the backend container and connect it to both networks
  community.docker.docker_container:
    name: backend
    image: lbonnieul/backend
    pull: yes
    env_file: /home/admin/.env
    env: 
      DB_NAME=DB_NAME
      DB_NAME=DB_USER
      DB_NAME=DB_PASSWORD
    networks:
      - name: network-database-backend

      - name: network-backend-frontend
    