---
# tasks file for roles/proxy
- name: Create the proxy container and connect to network
  docker_container:
    name: proxy
    image: lbonnieul/proxy:latest
    pull: yes
    networks:
      - name: network-backend-proxy
    ports:
      - "80:80"
      - "8080:8080"
    