name: build-push-docker-images
on:
  workflow_run:
    branches:
      - main
    workflows:
      - test-build-backend
    types:
      - completed
jobs:
  build-and-push-docker-image:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    # run only when code is compiling and tests are passing
    runs-on: ubuntu-22.04

    # steps to perform in job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.5.0

      - name: Login to DockerHub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Numero version
        run: echo "VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout --file backend/pom.xml)" >> $GITHUB_ENV

      - name: Build image and push backend
        uses: docker/build-push-action@v4
        with:
          # relative path to the place where source code with Dockerfile is located
          context: ./backend
          # Note: tags has to be all lower-case
          tags: ${{secrets.DOCKERHUB_USERNAME}}/backend:latest,
                ${{secrets.DOCKERHUB_USERNAME}}/backend:${{env.VERSION}}
          # build on feature branches, push only on main branch
          push: ${{ github.ref == 'refs/heads/main' }}

      - name: Build image and push database
        uses: docker/build-push-action@v4
        with:
          context: ./database
          tags: ${{secrets.DOCKERHUB_USERNAME}}/database:latest,
                ${{secrets.DOCKERHUB_USERNAME}}/database:${{env.VERSION}}
          # build on feature branches, push only on main branch
          push: ${{ github.ref == 'refs/heads/main' }}

      - name: Build image and push proxy
        uses: docker/build-push-action@v4
        with:
          context: ./proxy
          tags: ${{secrets.DOCKERHUB_USERNAME}}/proxy:latest,
                ${{secrets.DOCKERHUB_USERNAME}}/proxy:${{env.VERSION}}
          # build on feature branches, push only on main branch
          push: ${{ github.ref == 'refs/heads/main' }}